CREATE TABLE [dbo].[ApprovedCreditCard]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Number NVARCHAR(30) NOT NULL,
	Owner NVARCHAR(500) NOT NULL,
	CCV INT NOT NULL,
	ExpirationDateMMYY NVARCHAR(4) NOT NULL
)
