CREATE TABLE FeedbackForm
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	IsCurrent BIT DEFAULT(0),
	
	CreatedBy INT NOT NULL,
	UpdatedBy INT NOT NULL,
	CreatedDate SMALLDATETIME DEFAULT(GETUTCDATE()),
	UpdatedDate SMALLDATETIME DEFAULT(GETUTCDATE())
)
