CREATE TABLE PlatformUserPhone
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	PhoneTypeId INT NOT NULL,
	Number NVARCHAR(200) NOT NULL,
	UserId INT NOT NULL,
	[CreatedDate] SMALLDATETIME NOT NULL DEFAULT(GETDATE()),
	[CreatedBy] INT,
	[UpdatedDate] SMALLDATETIME NOT NULL DEFAULT(GETDATE()),
	[UpdatedBy] INT,

	FOREIGN KEY (PhoneTypeId) REFERENCES PhoneType,
	FOREIGN KEY (UserId) REFERENCES PlatformUser
)
