CREATE TABLE [dbo].[PricingPlanComment]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),

	Comment NVARCHAR(MAX) NOT NULL,
	CommentBy NVARCHAR(200) NOT NULL,
	PricingPlanId INT NOT NULL,
	Rating INT NOT NULL DEFAULT(1),

	CreatedBy INT NOT NULL,
	UpdatedBy INT NOT NULL,
	CreatedDate SMALLDATETIME DEFAULT(GETUTCDATE()),
	UpdatedDate SMALLDATETIME DEFAULT(GETUTCDATE()),

	FOREIGN KEY (PricingPlanId) REFERENCES PricingPlan
)
