CREATE TABLE SubmittedFeedbackForm
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	FeedbackFormId INT NOT NULL,

	CreatedBy INT NOT NULL,
	UpdatedBy INT NOT NULL,
	CreatedDate SMALLDATETIME DEFAULT(GETUTCDATE()),
	UpdatedDate SMALLDATETIME DEFAULT(GETUTCDATE())

	FOREIGN KEY (FeedbackFormId) REFERENCES FeedbackForm
)
