CREATE TABLE [dbo].[SurveyForm]
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	QuestionTitle NVARCHAR(500) NOT NULL,
	IsEnabled BIT NOT NULL DEFAULT(1),

	CreatedBy INT NOT NULL,
	UpdatedBy INT NOT NULL,
	CreatedDate SMALLDATETIME DEFAULT(GETUTCDATE()),
	UpdatedDate SMALLDATETIME DEFAULT(GETUTCDATE())
)
