CREATE TABLE [dbo].[SurveyChoice]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	SurveyFormId INT NOT NULL,
	ChoiceTitle NVARCHAR(100) NOT NULL,

	CreatedBy INT NOT NULL,
	UpdatedBy INT NOT NULL,
	CreatedDate SMALLDATETIME DEFAULT(GETUTCDATE()),
	UpdatedDate SMALLDATETIME DEFAULT(GETUTCDATE())

	FOREIGN KEY (SurveyFormId) REFERENCES SurveyForm
)
