INSERT Province ( Name )
VALUES
	('Ciudad Autónoma de Buenos Aires'),
	('Buenos Aires'),
	('Catamarca'),
	('Chaco'),
	('Chubut'),
	('Córdoba'),
	('Corrientes'),
	('Entre Ríos'),
	('Formosa'),
	('Jujuy'),
	('La Pampa'),
	('La Rioja'),
	('Mendoza'),
	('Neuquén'),
	('Río Negro'),
	('Salta'),
	('San Juan'),
	('Santa Cruz'),
	('Santa Fe'),
	('Santiago del Estero'),
	('Tierra del Fuego'),
	('Tucumán')